# Generated by Django 5.2 on 2025-04-27 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0001_initial'),
        ('direcciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('solicitado', models.DateTimeField(auto_now_add=True)),
                ('asignado', models.DateTimeField(blank=True, null=True)),
                ('completado', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado', models.IntegerField(blank=True, help_text='Tiempo estimado de llegada en minutos', null=True)),
                ('distancia', models.FloatField(blank=True, help_text='Distanvcia en kilómetros', null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cliente', to=settings.AUTH_USER_MODEL)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='conductores.conductor')),
                ('direccion_recogida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_recogida', to='direcciones.direccion')),
            ],
            options={
                'ordering': ['solicitado'],
            },
        ),
    ]
